
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\tModLoader.targets" />
  <PropertyGroup>
    <AssemblyName>AmmoboxPlus</AssemblyName>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="FNA">
      <HintPath>..\..\..\Steam\steamapps\common\tModLoader\Libraries\FNA\1.0.0\FNA.dll</HintPath>
    </Reference>
    <Reference Include="tModLoader">
      <HintPath>..\..\..\Steam\steamapps\common\tModLoader\tModLoader.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>